export * from './types.js'
export { TeachingEngine } from './engine.js'
export { ContextDetector } from './context-detector.js'
export { CandidateSelector } from './candidate-selector.js'
export { TechniqueFilter } from './filter.js'
export { ThompsonSamplingBandit } from './bandit.js'
export { BehaviorOrchestrator, BEHAVIORS } from './behaviors.js'
export { RAGEngine } from './rag.js'
export { PromptCompiler } from './prompt-compiler.js'
export { TECHNIQUE_PROMPTS, enrichTechnique } from './technique-library.js'
export { applySM2, previewIntervals, CHOICE_TO_QUALITY } from './sm2.js'
export type { SM2State, SM2Result, FlashcardChoice } from './sm2.js'
