// ============================================================================
// Kavra — 150 Teknik Seed Datası
// Dosya #1 + #2 + #3'ten çıkarılmış, M1-M7 + C1-C10 yapısında
// ============================================================================

export interface TechniqueSeed {
  code: string
  module_code: string
  name: string
  name_en?: string
  short_description: string
  long_description?: string
  kind: 'student_facing' | 'engine_behavior'
  suitable_for?: string[]
  difficulty_level?: number
  estimated_duration_minutes?: number
  ui_component?: string
  prompt_template?: string
  system_prompt?: string
  tags?: string[]
}

// ============================================================================
// M1 — HAFIZA VE KODLAMA (18 teknik)
// ============================================================================
const M1: TechniqueSeed[] = [
  {
    code: 'M1-T01',
    module_code: 'M1',
    name: 'Aktif Geri Çağırma',
    name_en: 'Active Recall',
    short_description: 'Notlara bakmadan bilgiyi zihinden çağırma.',
    kind: 'student_facing',
    suitable_for: ['review', 'weak_spot'],
    difficulty_level: 2,
    estimated_duration_minutes: 15,
    ui_component: 'flashcard',
  },
  {
    code: 'M1-T02',
    module_code: 'M1',
    name: 'Aralıklı Tekrar',
    name_en: 'Spaced Repetition',
    short_description: 'Artan zaman aralıklarıyla tekrar ederek unutma eğrisine karşı koyma.',
    kind: 'student_facing',
    suitable_for: ['review'],
    difficulty_level: 1,
    estimated_duration_minutes: 10,
    ui_component: 'flashcard',
  },
  {
    code: 'M1-T03',
    module_code: 'M1',
    name: 'Leitner Sistemi',
    name_en: 'Leitner System',
    short_description: 'Bilgi kartlarını 5 kutu arasında performansa göre taşıma.',
    kind: 'student_facing',
    suitable_for: ['review'],
    difficulty_level: 2,
    ui_component: 'flashcard',
  },
  {
    code: 'M1-T04',
    module_code: 'M1',
    name: 'Detaylandırarak Kodlama',
    name_en: 'Elaborative Interrogation',
    short_description: '"Bu neden doğru?" sorusuyla bilgiyi sorgulama.',
    kind: 'student_facing',
    suitable_for: ['first_exposure', 'practice'],
    difficulty_level: 3,
    ui_component: 'chat',
  },
  {
    code: 'M1-T05',
    module_code: 'M1',
    name: 'Çift Kodlama',
    name_en: 'Dual Coding',
    short_description: 'Bilgiyi hem sözel hem görsel materyallerle birleştirme.',
    kind: 'student_facing',
    suitable_for: ['first_exposure'],
    difficulty_level: 2,
    ui_component: 'chat',
  },
  {
    code: 'M1-T06',
    module_code: 'M1',
    name: 'Anımsatıcılar',
    name_en: 'Mnemonics',
    short_description: 'Kısaltmalar, akrostiş veya hikayelerle bilgi kodlama.',
    kind: 'student_facing',
    suitable_for: ['memorization'],
    difficulty_level: 2,
    ui_component: 'chat',
  },
  {
    code: 'M1-T07',
    module_code: 'M1',
    name: 'Görselleştirme',
    name_en: 'Visualization',
    short_description: 'Soyut kavramları zihinde somut görüntülere dönüştürme.',
    kind: 'student_facing',
    difficulty_level: 3,
    ui_component: 'chat',
  },
  {
    code: 'M1-T08',
    module_code: 'M1',
    name: 'Metafor Kullanımı',
    name_en: 'Metaphor',
    short_description: 'Yeni bilgiyi bilinen başka bir şeye benzeterek açıklama.',
    kind: 'student_facing',
    difficulty_level: 2,
    ui_component: 'chat',
  },
  {
    code: 'M1-T09',
    module_code: 'M1',
    name: 'Zihin Sarayı',
    name_en: 'Method of Loci',
    short_description: 'Bilgiyi tanıdık bir mekandaki nesnelere bağlayarak hatırlama.',
    kind: 'student_facing',
    difficulty_level: 4,
    estimated_duration_minutes: 30,
    ui_component: 'chat',
  },
  {
    code: 'M1-T10',
    module_code: 'M1',
    name: 'Akrostiş',
    name_en: 'Acrostic',
    short_description: 'Hatırlanacak bilginin baş harfleriyle anlamlı cümle oluşturma.',
    kind: 'student_facing',
    difficulty_level: 1,
    ui_component: 'chat',
  },
  {
    code: 'M1-T11',
    module_code: 'M1',
    name: 'Hikayeleştirme',
    name_en: 'Storytelling',
    short_description: 'Kavramları bir hikaye akışı içinde birleştirme.',
    kind: 'student_facing',
    difficulty_level: 3,
    ui_component: 'chat',
  },
  {
    code: 'M1-T12',
    module_code: 'M1',
    name: 'Parçalara Ayırma',
    name_en: 'Chunking',
    short_description: 'Uzun sayı veya listeleri anlamlı küçük gruplara ayırma.',
    kind: 'student_facing',
    difficulty_level: 1,
    ui_component: 'chat',
  },
  {
    code: 'M1-T13',
    module_code: 'M1',
    name: 'Zincirleme',
    name_en: 'Interlinking',
    short_description: 'Yeni bilgiyi daha önce öğrenilenlerle ilişkilendirme.',
    kind: 'student_facing',
    difficulty_level: 2,
    ui_component: 'mindmap',
  },
  {
    code: 'M1-T14',
    module_code: 'M1',
    name: 'Anlamsal Haritalama',
    name_en: 'Semantic Mapping',
    short_description: 'Kelimenin etrafına eş/zıt anlamlı ve çağrışımları yazma.',
    kind: 'student_facing',
    difficulty_level: 2,
    ui_component: 'mindmap',
  },
  {
    code: 'M1-T15',
    module_code: 'M1',
    name: 'Şiirsel Kodlama',
    name_en: 'Poetic Encoding',
    short_description: 'Zor terimleri kafiyeli şiir veya rap şarkıya çevirme.',
    kind: 'student_facing',
    difficulty_level: 3,
    ui_component: 'chat',
  },
  {
    code: 'M1-T16',
    module_code: 'M1',
    name: 'Pratik Transkripsiyon',
    name_en: 'Transcription Practice',
    short_description: 'Ders videosunu kelimesi kelimesine yazıya dökme.',
    kind: 'student_facing',
    difficulty_level: 2,
    ui_component: 'chat',
  },
  {
    code: 'M1-T17',
    module_code: 'M1',
    name: 'Yankı Tekniği',
    name_en: 'Shadowing',
    short_description: 'Ses kaydını milisaniye gecikmeyle yüksek sesle tekrar etme.',
    kind: 'student_facing',
    difficulty_level: 3,
    ui_component: 'chat',
  },
  {
    code: 'M1-T18',
    module_code: 'M1',
    name: 'Post-it Duvarı',
    name_en: 'Sticky Note Wall',
    short_description: 'Bilgiyi küçük kağıtlara yazıp sürekli pasif maruziyet sağlama.',
    kind: 'student_facing',
    difficulty_level: 1,
    ui_component: 'chat',
  },
]

// ============================================================================
// M2 — ÜSTBİLİŞ VE PLANLAMA (15 teknik)
// ============================================================================
const M2: TechniqueSeed[] = [
  {
    code: 'M2-T01',
    module_code: 'M2',
    name: 'Feynman Tekniği',
    name_en: 'Feynman Technique',
    short_description: 'Konuyu bir çocuğa anlatıyormuş gibi basit dille açıklama.',
    kind: 'student_facing',
    suitable_for: ['first_exposure', 'practice'],
    difficulty_level: 3,
    estimated_duration_minutes: 20,
    ui_component: 'chat',
    system_prompt:
      'Sen bir Sokratik öğretmensin. Öğrenci konuyu sana açıklayacak. Açıklamadaki boşlukları, basit çocuk sorularıyla öğrenciye göster.',
  },
  {
    code: 'M2-T02',
    module_code: 'M2',
    name: 'SQ3R Metodu',
    name_en: 'SQ3R Method',
    short_description: 'Oku, Sor, Oku, Anlat, Gözden Geçir adımlarıyla aktif okuma.',
    kind: 'student_facing',
    suitable_for: ['first_exposure'],
    difficulty_level: 2,
    estimated_duration_minutes: 45,
    ui_component: 'chat',
  },
  {
    code: 'M2-T03',
    module_code: 'M2',
    name: 'Öz Değerlendirme',
    name_en: 'Self-Assessment',
    short_description: 'Kendi bilgi seviyesini test etme ve eksikleri belirleme.',
    kind: 'student_facing',
    difficulty_level: 2,
    ui_component: 'quiz',
  },
  {
    code: 'M2-T04',
    module_code: 'M2',
    name: 'Yansıtıcı Günlük',
    name_en: 'Reflective Journal',
    short_description: 'O gün ne öğrenildiğini, neyin zor geldiğini yazma.',
    kind: 'student_facing',
    difficulty_level: 1,
    ui_component: 'journal',
  },
  {
    code: 'M2-T05',
    module_code: 'M2',
    name: 'Bloom Taksonomisi',
    name_en: 'Bloom Taxonomy',
    short_description: 'Öğrenme hedeflerini basitten karmaşığa sıralama.',
    kind: 'student_facing',
    difficulty_level: 3,
    ui_component: 'chat',
  },
  {
    code: 'M2-T06',
    module_code: 'M2',
    name: 'Hedef Belirleme',
    name_en: 'Goal Setting',
    short_description: 'Net, ölçülebilir, ulaşılabilir hedefler koyma.',
    kind: 'student_facing',
    difficulty_level: 1,
    ui_component: 'chat',
  },
  {
    code: 'M2-T07',
    module_code: 'M2',
    name: 'Sokratik Sorgulama',
    name_en: 'Socratic Questioning',
    short_description: '"Bu ne anlama geliyor?" "Kanıt ne?" "Alternatif?" soruları.',
    kind: 'student_facing',
    difficulty_level: 3,
    ui_component: 'chat',
  },
  {
    code: 'M2-T08',
    module_code: 'M2',
    name: 'Sesli Düşünme',
    name_en: 'Think Aloud',
    short_description: 'Problem çözerken düşünceleri sesli kaydetme ve analiz.',
    kind: 'student_facing',
    difficulty_level: 2,
    ui_component: 'chat',
  },
  {
    code: 'M2-T09',
    module_code: 'M2',
    name: 'Kendine Öğretme',
    name_en: 'Self-Explanation',
    short_description: 'Problemi çözerken ne yaptığını sesli anlatma.',
    kind: 'student_facing',
    difficulty_level: 2,
    ui_component: 'chat',
  },
  {
    code: 'M2-T10',
    module_code: 'M2',
    name: 'Ayna Karşısında Anlatma',
    name_en: 'Mirror Teaching',
    short_description: 'Konuyu ayna karşısında kendine anlatma.',
    kind: 'student_facing',
    difficulty_level: 1,
    ui_component: 'chat',
  },
  {
    code: 'M2-T11',
    module_code: 'M2',
    name: 'Öngörücü Yazma',
    name_en: 'Predictive Writing',
    short_description: 'Cümleye başla, AI tamamlasın, yanlışsa düzelt.',
    kind: 'student_facing',
    difficulty_level: 3,
    ui_component: 'chat',
  },
  {
    code: 'M2-T12',
    module_code: 'M2',
    name: 'Özet Çıkarma',
    name_en: 'Summarization',
    short_description: 'Metni kendi cümlelerinle ana hatlarıyla yeniden yazma.',
    kind: 'student_facing',
    difficulty_level: 2,
    ui_component: 'chat',
  },
  {
    code: 'M2-T13',
    module_code: 'M2',
    name: 'Sentezleme',
    name_en: 'Synthesis',
    short_description: 'Farklı kaynakları birleştirerek yeni bütün oluşturma.',
    kind: 'student_facing',
    difficulty_level: 4,
    ui_component: 'chat',
  },
  {
    code: 'M2-T14',
    module_code: 'M2',
    name: 'Yabancı Dilde Düşünme',
    name_en: 'Thinking in Target Language',
    short_description: 'Öğrenilen dilde iç konuşmalar yapma.',
    kind: 'student_facing',
    difficulty_level: 3,
    ui_component: 'chat',
  },
  {
    code: 'M2-T15',
    module_code: 'M2',
    name: 'Dikte Çalışması',
    name_en: 'Dictogloss',
    short_description: 'Dinlenen metni ana fikirleriyle yeniden yapılandırma.',
    kind: 'student_facing',
    difficulty_level: 3,
    ui_component: 'chat',
  },
]

// ============================================================================
// M3 — UYGULAMA VE PEKİŞTİRME (15 teknik)
// ============================================================================
const M3: TechniqueSeed[] = [
  {
    code: 'M3-T01',
    module_code: 'M3',
    name: 'Problem Çözme Odaklı Çalışma',
    name_en: 'Problem-Based Learning',
    short_description: 'Sadece teori değil, bol bol problem ve test çözme.',
    kind: 'student_facing',
    difficulty_level: 3,
    ui_component: 'quiz',
  },
  {
    code: 'M3-T02',
    module_code: 'M3',
    name: 'Pratik Testler',
    name_en: 'Practice Testing',
    short_description: 'Gerçek sınav formatında düzenli testler çözme.',
    kind: 'student_facing',
    difficulty_level: 2,
    ui_component: 'quiz',
  },
  {
    code: 'M3-T03',
    module_code: 'M3',
    name: 'Tersine Mühendislik',
    name_en: 'Reverse Engineering',
    short_description: 'Bitmiş bir çözümü inceleyerek nasıl yapıldığını anlama.',
    kind: 'student_facing',
    difficulty_level: 4,
    ui_component: 'chat',
  },
  {
    code: 'M3-T04',
    module_code: 'M3',
    name: 'Vaka Çalışması',
    name_en: 'Case Study',
    short_description: 'Gerçek hayattan olayı tüm detaylarıyla inceleme.',
    kind: 'student_facing',
    difficulty_level: 3,
    ui_component: 'chat',
  },
  {
    code: 'M3-T05',
    module_code: 'M3',
    name: 'İç İçe Geçirme',
    name_en: 'Interleaving',
    short_description: 'Tek konu yerine farklı konuları/problem tiplerini karıştırma.',
    kind: 'student_facing',
    difficulty_level: 3,
    ui_component: 'quiz',
  },
  {
    code: 'M3-T06',
    module_code: 'M3',
    name: 'Rol Yapma',
    name_en: 'Role Playing',
    short_description: 'Tarihi figür veya bilim insanı gibi davranarak konuyu canlandırma.',
    kind: 'student_facing',
    difficulty_level: 2,
    ui_component: 'chat',
  },
  {
    code: 'M3-T07',
    module_code: 'M3',
    name: 'Kinestetik Öğrenme',
    name_en: 'Kinesthetic Learning',
    short_description: 'Öğrenirken hareket etme, yürüme veya model yapma.',
    kind: 'student_facing',
    difficulty_level: 1,
    ui_component: 'chat',
  },
  {
    code: 'M3-T08',
    module_code: 'M3',
    name: 'Yürüme Toplantısı',
    name_en: 'Walk and Talk',
    short_description: 'Ezber yaparken dışarıda tempolu yürüme.',
    kind: 'student_facing',
    difficulty_level: 1,
    ui_component: 'chat',
  },
  {
    code: 'M3-T09',
    module_code: 'M3',
    name: 'Lego ile Modelleme',
    name_en: 'Physical Modeling',
    short_description: 'Kimyasal bağları, şekilleri somut nesnelerle inşa etme.',
    kind: 'student_facing',
    difficulty_level: 2,
    ui_component: 'chat',
  },
  {
    code: 'M3-T10',
    module_code: 'M3',
    name: 'Parmak Alfabesi',
    name_en: 'Fingerspelling',
    short_description: 'Yabancı dil veya formül ezberinde parmakla havada yazma.',
    kind: 'student_facing',
    difficulty_level: 1,
    ui_component: 'chat',
  },
  {
    code: 'M3-T11',
    module_code: 'M3',
    name: 'Flip Chart Sunumu',
    name_en: 'Flip Chart Presentation',
    short_description: 'Tahtada konferans verir gibi ders anlatma.',
    kind: 'student_facing',
    difficulty_level: 2,
    ui_component: 'chat',
  },
  {
    code: 'M3-T12',
    module_code: 'M3',
    name: 'El Notu Hazırlama',
    name_en: 'Study Guide Creation',
    short_description: 'Konuyu profesyonel 1 sayfalık rehber olarak tasarlama.',
    kind: 'student_facing',
    difficulty_level: 2,
    ui_component: 'chat',
  },
  {
    code: 'M3-T13',
    module_code: 'M3',
    name: 'Eş Zamanlı Çeviri',
    name_en: 'Real-time Translation Practice',
    short_description: "Yabancı dildeki podcast'i anlık çevirme.",
    kind: 'student_facing',
    difficulty_level: 4,
    ui_component: 'chat',
  },
  {
    code: 'M3-T14',
    module_code: 'M3',
    name: 'Propriyoseptif Girdi',
    name_en: 'Proprioceptive Input',
    short_description: 'Öğrenirken kas/eklem çalıştıran aktivitelerle odaklanma.',
    kind: 'student_facing',
    difficulty_level: 2,
    ui_component: 'chat',
  },
  {
    code: 'M3-T15',
    module_code: 'M3',
    name: 'Beyin Jimnastiği',
    name_en: 'Brain Gym',
    short_description: 'Çapraz kol-bacak hareketleriyle beyin loblarını aktive etme.',
    kind: 'student_facing',
    difficulty_level: 1,
    ui_component: 'chat',
  },
]

// ============================================================================
// M4 — NOT ALMA VE GÖRSELLEŞTİRME (16 teknik)
// ============================================================================
const M4: TechniqueSeed[] = [
  {
    code: 'M4-T01',
    module_code: 'M4',
    name: 'Cornell Not Tutma',
    name_en: 'Cornell Notes',
    short_description: 'Sayfayı bölerek anahtar kelimeler, notlar ve özet alanı.',
    kind: 'student_facing',
    difficulty_level: 2,
    ui_component: 'journal',
  },
  {
    code: 'M4-T02',
    module_code: 'M4',
    name: 'Zihin Haritalama',
    name_en: 'Mind Mapping',
    short_description: 'Ana fikirden dallara ayrılan görsel şema.',
    kind: 'student_facing',
    difficulty_level: 2,
    ui_component: 'mindmap',
  },
  {
    code: 'M4-T03',
    module_code: 'M4',
    name: 'Kavram Haritası',
    name_en: 'Concept Mapping',
    short_description: 'Bilgiler arası ilişkiyi hiyerarşik yapıda gösterme.',
    kind: 'student_facing',
    difficulty_level: 3,
    ui_component: 'mindmap',
  },
  {
    code: 'M4-T04',
    module_code: 'M4',
    name: 'Kutu ve İşaretleme',
    name_en: 'Boxing & Bullets',
    short_description: 'Notları kutularla veya madde işaretiyle gruplandırma.',
    kind: 'student_facing',
    difficulty_level: 1,
    ui_component: 'journal',
  },
  {
    code: 'M4-T05',
    module_code: 'M4',
    name: 'Akış Şeması',
    name_en: 'Flow Chart',
    short_description: 'Süreçleri ve olay sırasını görsel takip.',
    kind: 'student_facing',
    difficulty_level: 2,
    ui_component: 'mindmap',
  },
  {
    code: 'M4-T06',
    module_code: 'M4',
    name: 'Eskiz Notlama',
    name_en: 'Sketchnoting',
    short_description: 'İkonlar, figürler, oklar ve kutularla sanat eseri notlar.',
    kind: 'student_facing',
    difficulty_level: 3,
    ui_component: 'journal',
  },
  {
    code: 'M4-T07',
    module_code: 'M4',
    name: 'Çizgi Romanlaştırma',
    name_en: 'Comic Strip',
    short_description: 'Tarihi olayı veya süreci 3-4 karelik çizgi romana çevirme.',
    kind: 'student_facing',
    difficulty_level: 3,
    ui_component: 'chat',
  },
  {
    code: 'M4-T08',
    module_code: 'M4',
    name: 'Venn Şeması',
    name_en: 'Venn Diagram',
    short_description: 'İki kavram arası fark/ortak noktayı kesişen dairelerle.',
    kind: 'student_facing',
    difficulty_level: 1,
    ui_component: 'mindmap',
  },
  {
    code: 'M4-T09',
    module_code: 'M4',
    name: 'Veri Görselleştirme',
    name_en: 'Data Visualization',
    short_description: 'İstatistikleri çubuk/pasta grafik elle çizerek betimleme.',
    kind: 'student_facing',
    difficulty_level: 2,
    ui_component: 'chat',
  },
  {
    code: 'M4-T10',
    module_code: 'M4',
    name: 'Zaman Çizelgesi',
    name_en: 'Timeline',
    short_description: 'Tarih olaylarını yatay çizgide kronolojik işaretleme.',
    kind: 'student_facing',
    difficulty_level: 1,
    ui_component: 'mindmap',
  },
  {
    code: 'M4-T11',
    module_code: 'M4',
    name: 'Yapı Taşı Diyagramı',
    name_en: 'Block Diagram',
    short_description: 'Karmaşık sistem parçalarını iç içe bloklarla.',
    kind: 'student_facing',
    difficulty_level: 3,
    ui_component: 'mindmap',
  },
  {
    code: 'M4-T12',
    module_code: 'M4',
    name: 'Grafik Düzenleyiciler',
    name_en: 'Graphic Organizers',
    short_description: 'Sebep-sonuç, problem-çözüm şablonları.',
    kind: 'student_facing',
    difficulty_level: 2,
    ui_component: 'mindmap',
  },
  {
    code: 'M4-T13',
    module_code: 'M4',
    name: 'Sembolik Kısaltma',
    name_en: 'Symbolic Shorthand',
    short_description: 'Kendine özel hiyeroglif alfabesi (↑↓∴).',
    kind: 'student_facing',
    difficulty_level: 2,
    ui_component: 'journal',
  },
  {
    code: 'M4-T14',
    module_code: 'M4',
    name: 'Akıcı Notlar',
    name_en: 'Fluid Notes',
    short_description: 'Klasik yerine sayfa üzerinde serbest bağlantılar.',
    kind: 'student_facing',
    difficulty_level: 2,
    ui_component: 'journal',
  },
  {
    code: 'M4-T15',
    module_code: 'M4',
    name: 'Argüman Haritalama',
    name_en: 'Argument Mapping',
    short_description: 'Metindeki iddiaları, destekleyicileri ve itirazları ağaçta gösterme.',
    kind: 'student_facing',
    difficulty_level: 4,
    ui_component: 'mindmap',
  },
  {
    code: 'M4-T16',
    module_code: 'M4',
    name: 'Dijital Zettelkasten',
    name_en: 'Digital Zettelkasten',
    short_description: 'Notları bağlantılı dijital ağ olarak tutma.',
    kind: 'student_facing',
    difficulty_level: 3,
    ui_component: 'mindmap',
  },
]

// ============================================================================
// M5 — SOSYAL VE İŞBİRLİKÇİ (12 teknik - AI ile uyarlanmış)
// ============================================================================
const M5: TechniqueSeed[] = [
  {
    code: 'M5-T01',
    module_code: 'M5',
    name: 'Akran Öğretimi (AI)',
    name_en: 'Peer Teaching with AI',
    short_description: "AI'yı öğrenci gibi kabul edip öğrettiğin konuyu ona anlatma.",
    kind: 'student_facing',
    difficulty_level: 3,
    ui_component: 'chat',
    system_prompt:
      'Sen meraklı ama bilgisiz bir öğrencisin. Kullanıcı sana konuyu anlatacak. Anlamadığın yerleri çocukça sorularla sor.',
  },
  {
    code: 'M5-T02',
    module_code: 'M5',
    name: 'Münazara (AI vs User)',
    name_en: 'Debate with AI',
    short_description: 'AI karşı argüman üretir, sen pozisyonunu savunursun.',
    kind: 'student_facing',
    difficulty_level: 4,
    ui_component: 'chat',
    system_prompt:
      'Sen sıkı bir münazara rakibisin. Kullanıcının her argümanına karşı mantıklı itirazlar üret.',
  },
  {
    code: 'M5-T03',
    module_code: 'M5',
    name: 'Tartışma Grupları',
    name_en: 'Buzz Groups',
    short_description: 'AI birden fazla uzman rolü alıp tartışma simüle eder.',
    kind: 'student_facing',
    difficulty_level: 3,
    ui_component: 'chat',
  },
  {
    code: 'M5-T04',
    module_code: 'M5',
    name: 'Beyin Fırtınası',
    name_en: 'Brainstorming',
    short_description: 'AI ile birlikte yargılamadan fikir üretme.',
    kind: 'student_facing',
    difficulty_level: 1,
    ui_component: 'chat',
  },
  {
    code: 'M5-T05',
    module_code: 'M5',
    name: 'AI Sokratik Tutor',
    name_en: 'AI Socratic Tutor',
    short_description: 'Konuyu direkt anlatmak yerine soru-cevapla öğretme.',
    kind: 'student_facing',
    difficulty_level: 3,
    ui_component: 'chat',
  },
  {
    code: 'M5-T06',
    module_code: 'M5',
    name: 'Altı Şapkalı Düşünme',
    name_en: 'Six Thinking Hats',
    short_description: 'Konuyu 6 farklı rol (duygusal, mantıksal, yaratıcı vs) ile analiz.',
    kind: 'student_facing',
    difficulty_level: 4,
    ui_component: 'chat',
  },
  {
    code: 'M5-T07',
    module_code: 'M5',
    name: 'AI Sorumluluk Ortağı',
    name_en: 'AI Accountability Buddy',
    short_description: 'AI belli saatte seni arayıp öğrendiğin konuyu sorar.',
    kind: 'student_facing',
    difficulty_level: 1,
    ui_component: 'chat',
  },
  {
    code: 'M5-T08',
    module_code: 'M5',
    name: 'Sanal Odaklanma',
    name_en: 'Virtual Focus Room',
    short_description: 'AI ile paralel çalışma disiplini, düzenli check-in.',
    kind: 'student_facing',
    difficulty_level: 1,
    ui_component: 'focus',
  },
  {
    code: 'M5-T09',
    module_code: 'M5',
    name: 'Çoklu Perspektif',
    name_en: 'Multi-Perspective',
    short_description: 'AI aynı olayı 3 farklı görüşten anlatır.',
    kind: 'student_facing',
    difficulty_level: 3,
    ui_component: 'chat',
  },
  {
    code: 'M5-T10',
    module_code: 'M5',
    name: 'Forum Simülasyonu',
    name_en: 'Forum Simulation',
    short_description: 'AI Stack Overflow/Reddit tarzı topluluğu canlandırır.',
    kind: 'student_facing',
    difficulty_level: 2,
    ui_component: 'chat',
  },
  {
    code: 'M5-T11',
    module_code: 'M5',
    name: 'Rol Yapma Diyaloğu',
    name_en: 'Role-Play Dialogue',
    short_description: 'AI tarihi/kurgusal karakteri canlandırır, sen diyaloğa girersin.',
    kind: 'student_facing',
    difficulty_level: 3,
    ui_component: 'chat',
  },
  {
    code: 'M5-T12',
    module_code: 'M5',
    name: 'Üçüncü Tarafa Açıklama',
    name_en: 'Third-Party Explanation',
    short_description: 'AI 3. karakter rolü alır, sen iki kişi arasında konuyu açıklarsın.',
    kind: 'student_facing',
    difficulty_level: 3,
    ui_component: 'chat',
  },
]

// ============================================================================
// M6 — ODAKLANMA VE ZİHİN YÖNETİMİ (14 teknik)
// ============================================================================
const M6: TechniqueSeed[] = [
  {
    code: 'M6-T01',
    module_code: 'M6',
    name: 'Pomodoro Tekniği',
    name_en: 'Pomodoro Technique',
    short_description: '25 dk odak + 5 dk mola döngüleri.',
    kind: 'student_facing',
    difficulty_level: 1,
    ui_component: 'focus',
  },
  {
    code: 'M6-T02',
    module_code: 'M6',
    name: 'Zaman Bloklama',
    name_en: 'Time Blocking',
    short_description: 'Gün içinde belirli saatleri tek konuya ayırma.',
    kind: 'student_facing',
    difficulty_level: 2,
    ui_component: 'focus',
  },
  {
    code: 'M6-T03',
    module_code: 'M6',
    name: '5 Dakika Kuralı',
    name_en: '5 Minute Rule',
    short_description: 'Ertelemede sadece 5 dk başlama anlaşması.',
    kind: 'student_facing',
    difficulty_level: 1,
    ui_component: 'focus',
  },
  {
    code: 'M6-T04',
    module_code: 'M6',
    name: 'Eisenhower Matrisi',
    name_en: 'Eisenhower Matrix',
    short_description: 'Görevleri aciliyet-önem matrisinde sıralama.',
    kind: 'student_facing',
    difficulty_level: 2,
    ui_component: 'chat',
  },
  {
    code: 'M6-T05',
    module_code: 'M6',
    name: 'Dikkat Dağıtıcı Yönetimi',
    name_en: 'Distraction Management',
    short_description: 'Telefon, gereksiz sekme, bildirim kaldırma.',
    kind: 'student_facing',
    difficulty_level: 1,
    ui_component: 'focus',
  },
  {
    code: 'M6-T06',
    module_code: 'M6',
    name: 'Dijital Detoks',
    name_en: 'Digital Detox',
    short_description: 'Belirli saatlerde internet tamamen kesme.',
    kind: 'student_facing',
    difficulty_level: 2,
    ui_component: 'focus',
  },
  {
    code: 'M6-T07',
    module_code: 'M6',
    name: 'Mekan Çapalama',
    name_en: 'Spatial Anchoring',
    short_description: 'Her konuyu farklı köşede çalışarak mekansal hafıza.',
    kind: 'student_facing',
    difficulty_level: 2,
    ui_component: 'chat',
  },
  {
    code: 'M6-T08',
    module_code: 'M6',
    name: 'Müzikle Ayrıştırma',
    name_en: 'Music Tempo Matching',
    short_description: 'Çalışma hızına göre müzik temposu ayarlama.',
    kind: 'student_facing',
    difficulty_level: 1,
    ui_component: 'focus',
  },
  {
    code: 'M6-T09',
    module_code: 'M6',
    name: 'Beyaz Gürültü',
    name_en: 'White Noise',
    short_description: 'Arka planda odaklanma seviyesine göre ses.',
    kind: 'student_facing',
    difficulty_level: 1,
    ui_component: 'focus',
  },
  {
    code: 'M6-T10',
    module_code: 'M6',
    name: 'Piksel Takibi',
    name_en: 'Habit Tracking',
    short_description: 'Takvimde işaretleyerek zincir kırmama.',
    kind: 'student_facing',
    difficulty_level: 1,
    ui_component: 'chat',
  },
  {
    code: 'M6-T11',
    module_code: 'M6',
    name: 'Oyunlaştırma',
    name_en: 'Gamification',
    short_description: 'Puan, seviye, rozetlerle motive olma.',
    kind: 'student_facing',
    difficulty_level: 1,
    ui_component: 'chat',
  },
  {
    code: 'M6-T12',
    module_code: 'M6',
    name: 'Derin Çalışma',
    name_en: 'Deep Work',
    short_description: 'Kesintisiz 90 dk odaklanma seansı.',
    kind: 'student_facing',
    difficulty_level: 3,
    ui_component: 'focus',
  },
  {
    code: 'M6-T13',
    module_code: 'M6',
    name: 'Önceliklendirme',
    name_en: 'Prioritization',
    short_description: 'Günlük görevlerin önem sırası.',
    kind: 'student_facing',
    difficulty_level: 1,
    ui_component: 'chat',
  },
  {
    code: 'M6-T14',
    module_code: 'M6',
    name: 'Metni Sese Çevirme',
    name_en: 'Text to Speech',
    short_description: "Uzun PDF'leri dinleyerek işitsel öğrenme.",
    kind: 'student_facing',
    difficulty_level: 1,
    ui_component: 'chat',
  },
]

// ============================================================================
// M7 — ZİHİNSEL MODELLER VE MANTIK (10 teknik)
// ============================================================================
const M7: TechniqueSeed[] = [
  {
    code: 'M7-T01',
    module_code: 'M7',
    name: 'İlk Prensipler',
    name_en: 'First Principles',
    short_description: 'Konuyu tartışılmaz doğrularına indirgeyip yeniden inşa.',
    kind: 'student_facing',
    difficulty_level: 5,
    ui_component: 'chat',
  },
  {
    code: 'M7-T02',
    module_code: 'M7',
    name: 'Tersine Öğrenme',
    name_en: 'Inversion',
    short_description: '"Başarısız olmak isteseydim ne yapardım?" sorusuyla hataları tespit.',
    kind: 'student_facing',
    difficulty_level: 4,
    ui_component: 'chat',
  },
  {
    code: 'M7-T03',
    module_code: 'M7',
    name: "Ockham'ın Usturası",
    name_en: "Occam's Razor",
    short_description: 'Birden fazla çözüm varsa en basit olanı tercih et.',
    kind: 'student_facing',
    difficulty_level: 3,
    ui_component: 'chat',
  },
  {
    code: 'M7-T04',
    module_code: 'M7',
    name: 'İkinci Derece Düşünme',
    name_en: 'Second-Order Thinking',
    short_description: 'Anlık sonuçtan sonra zincirin ikinci halkasını düşünme.',
    kind: 'student_facing',
    difficulty_level: 4,
    ui_component: 'chat',
  },
  {
    code: 'M7-T05',
    module_code: 'M7',
    name: 'Harita Arazi Değildir',
    name_en: 'Map is Not the Territory',
    short_description: 'Teorilerin gerçek dünyanın tam kopyası olmadığını hatırlama.',
    kind: 'student_facing',
    difficulty_level: 3,
    ui_component: 'chat',
  },
  {
    code: 'M7-T06',
    module_code: 'M7',
    name: 'Çember Yetkinliği',
    name_en: 'Circle of Competence',
    short_description: 'Ne bilip ne bilmediğinin sınırlarını çizme.',
    kind: 'student_facing',
    difficulty_level: 3,
    ui_component: 'chat',
  },
  {
    code: 'M7-T07',
    module_code: 'M7',
    name: 'Düşünce Deneyi',
    name_en: 'Thought Experiment',
    short_description: 'Hipotezi zihinde mantıksal senaryoyla test etme.',
    kind: 'student_facing',
    difficulty_level: 4,
    ui_component: 'chat',
  },
  {
    code: 'M7-T08',
    module_code: 'M7',
    name: 'Bayesçi Güncelleme',
    name_en: 'Bayesian Updating',
    short_description: 'Yeni kanıta göre eski inançları matematiksel güncelleme.',
    kind: 'student_facing',
    difficulty_level: 5,
    ui_component: 'chat',
  },
  {
    code: 'M7-T09',
    module_code: 'M7',
    name: 'Sistem Düşüncesi',
    name_en: 'Systems Thinking',
    short_description: 'Olayı izole değil, bağlantılı sistemin çıktısı olarak görme.',
    kind: 'student_facing',
    difficulty_level: 4,
    ui_component: 'mindmap',
  },
  {
    code: 'M7-T10',
    module_code: 'M7',
    name: 'Regresyon Mantığı',
    name_en: 'Regression to Mean',
    short_description: 'Ortalamaya dönüş eğilimini hesaba katma.',
    kind: 'student_facing',
    difficulty_level: 4,
    ui_component: 'chat',
  },
]

// ============================================================================
// C1-C10 — AI KATEGORİLERİ (50 engine_behavior)
// ============================================================================
const C1: TechniqueSeed[] = [
  {
    code: 'C1-T01',
    module_code: 'C1',
    name: 'Dinamik Zorluk',
    name_en: 'Desirable Difficulty',
    short_description: 'Engine: başarı oranına göre zorluğu mikro-ayarlama.',
    kind: 'engine_behavior',
  },
  {
    code: 'C1-T02',
    module_code: 'C1',
    name: 'Niş Unutma Eğrisi',
    name_en: 'Niche Forgetting Curve',
    short_description: 'Engine: kavram başına özel unutma hızı.',
    kind: 'engine_behavior',
  },
  {
    code: 'C1-T03',
    module_code: 'C1',
    name: 'Semantik Boşluk',
    name_en: 'Semantic Gap Detection',
    short_description: 'Engine: eksik mantık bağlaçlarını tespit.',
    kind: 'engine_behavior',
  },
  {
    code: 'C1-T04',
    module_code: 'C1',
    name: 'Yanlış Madenciliği',
    name_en: 'Misconception Mining',
    short_description: 'Engine: tekrarlayan hatalardan "X\'i Y ile karıştırıyorsun" çıkarımı.',
    kind: 'engine_behavior',
  },
  {
    code: 'C1-T05',
    module_code: 'C1',
    name: 'Çoklu Zeka Profili',
    name_en: 'Multiple Intelligence Profiling',
    short_description: 'Engine: format başarısını izleyip içerik türü önerme.',
    kind: 'engine_behavior',
  },
]
const C2: TechniqueSeed[] = [
  {
    code: 'C2-T01',
    module_code: 'C2',
    name: 'Kayıptan Kaçınma',
    name_en: 'Loss Aversion Framing',
    short_description: 'Engine: "kazanç" yerine "kayıp" çerçevesiyle bildirim.',
    kind: 'engine_behavior',
  },
  {
    code: 'C2-T02',
    module_code: 'C2',
    name: 'Zirve-Son Kuralı',
    name_en: 'Peak-End Rule',
    short_description: 'Engine: seansı başarı/komik bilgiyle bitirme.',
    kind: 'engine_behavior',
  },
  {
    code: 'C2-T03',
    module_code: 'C2',
    name: 'Sorumluluk Ortağı',
    name_en: 'Accountability Buddy',
    short_description: 'Engine: "Yarın 14:00\'te seni arayacağım" taahhütleri.',
    kind: 'engine_behavior',
  },
  {
    code: 'C2-T04',
    module_code: 'C2',
    name: 'IKEA Etkisi',
    name_en: 'IKEA Effect',
    short_description: 'Engine: eksik parça verip kullanıcıya tamamlatma.',
    kind: 'engine_behavior',
  },
  {
    code: 'C2-T05',
    module_code: 'C2',
    name: 'Kıtlık Prensibi',
    name_en: 'Scarcity Principle',
    short_description: 'Engine: sınırlı "Uzman Modu" erişimi ile algılanan değer.',
    kind: 'engine_behavior',
  },
]
const C3: TechniqueSeed[] = [
  {
    code: 'C3-T01',
    module_code: 'C3',
    name: 'Ters Yüz Sınıf',
    name_en: 'Flipped Classroom',
    short_description: 'Engine: teori önce, problem çözme sonra.',
    kind: 'engine_behavior',
  },
  {
    code: 'C3-T02',
    module_code: 'C3',
    name: 'Geriye Zincirleme',
    name_en: 'Backward Chaining',
    short_description: 'Engine: son adımdan başlayıp geriye doğru öğretme.',
    kind: 'engine_behavior',
  },
  {
    code: 'C3-T03',
    module_code: 'C3',
    name: 'Kırmızı Ringa',
    name_en: 'Red Herring',
    short_description: 'Engine: dikkat testi için alakasız detay yerleştirme.',
    kind: 'engine_behavior',
  },
  {
    code: 'C3-T04',
    module_code: 'C3',
    name: 'Scaffolding Fading',
    name_en: 'Scaffolding Fading',
    short_description: 'Engine: %80 ipucu → %50 → %10 kademeli azaltma.',
    kind: 'engine_behavior',
  },
  {
    code: 'C3-T05',
    module_code: 'C3',
    name: 'Bilişsel Çıraklık',
    name_en: 'Cognitive Apprenticeship',
    short_description: 'Engine: AI kendi düşünce sesini açar.',
    kind: 'engine_behavior',
  },
]
const C4: TechniqueSeed[] = [
  {
    code: 'C4-T01',
    module_code: 'C4',
    name: 'Kavram Melezleme',
    name_en: 'Concept Blending',
    short_description: 'Engine: fizik kuralını tarih olayıyla açıklama.',
    kind: 'engine_behavior',
  },
  {
    code: 'C4-T02',
    module_code: 'C4',
    name: 'Çapa Hikaye',
    name_en: 'Anchor Story',
    short_description: 'Engine: tüm müfredatı tek büyük hikayeye yedirme.',
    kind: 'engine_behavior',
  },
  {
    code: 'C4-T03',
    module_code: 'C4',
    name: 'Çözünürlük',
    name_en: 'Resolution Zoom',
    short_description: 'Engine: 1dk → 5dk → 30dk detay versiyonları.',
    kind: 'engine_behavior',
  },
  {
    code: 'C4-T04',
    module_code: 'C4',
    name: 'Sokak vs Okul Bilgisi',
    name_en: 'Street vs School',
    short_description: 'Engine: teorinin gerçek hayat istisnalarını gösterme.',
    kind: 'engine_behavior',
  },
  {
    code: 'C4-T05',
    module_code: 'C4',
    name: 'Etimolojik Kök',
    name_en: 'Etymology',
    short_description: 'Engine: terimlerin Latin/Yunan kökünü gösterip dağarcık genişletme.',
    kind: 'engine_behavior',
  },
]
const C5: TechniqueSeed[] = [
  {
    code: 'C5-T01',
    module_code: 'C5',
    name: 'Yeniden Değerlendirme',
    name_en: 'Cognitive Reappraisal',
    short_description: 'Engine: "sıkıcı" → "bu konunun en tuhaf gerçeği ne?"',
    kind: 'engine_behavior',
  },
  {
    code: 'C5-T02',
    module_code: 'C5',
    name: 'Hassas Maruz Bırakma',
    name_en: 'Gentle Exposure',
    short_description: 'Engine: korkulan dersin sembollerini oyunlaştırma.',
    kind: 'engine_behavior',
  },
  {
    code: 'C5-T03',
    module_code: 'C5',
    name: 'Öngörücü Yazma',
    name_en: 'Predictive Writing',
    short_description: 'Engine: cümleyi tahmin eder, kullanıcı düzeltir.',
    kind: 'engine_behavior',
  },
  {
    code: 'C5-T04',
    module_code: 'C5',
    name: 'Gürültü Katmanlama',
    name_en: 'Noise Layering',
    short_description: 'Engine: sesli anlatıma dinamik beyaz gürültü ekleme.',
    kind: 'engine_behavior',
  },
  {
    code: 'C5-T05',
    module_code: 'C5',
    name: 'Sessizlik Protokolü',
    name_en: 'Silence Protocol',
    short_description: 'Engine: soru sonrası en az 10 sn bekleme.',
    kind: 'engine_behavior',
  },
]
const C6: TechniqueSeed[] = [
  {
    code: 'C6-T01',
    module_code: 'C6',
    name: 'Bloom İkili Geçiş',
    name_en: 'Bloom Dual-Pass',
    short_description: 'Engine: aynı metni "hatırla" + "değerlendir" seviyesinde sor.',
    kind: 'engine_behavior',
  },
  {
    code: 'C6-T02',
    module_code: 'C6',
    name: 'Sinyal-Gürültü',
    name_en: 'Signal-Noise Extractor',
    short_description: 'Engine: 20 sayfadan en kritik 3 cümleyi çekme.',
    kind: 'engine_behavior',
  },
  {
    code: 'C6-T03',
    module_code: 'C6',
    name: 'Çoklu Perspektif',
    name_en: 'Multi-Perspective Framing',
    short_description: 'Engine: aynı olayı 3 farklı gözden anlatma.',
    kind: 'engine_behavior',
  },
  {
    code: 'C6-T04',
    module_code: 'C6',
    name: 'Analog Veritabanı',
    name_en: 'Analogy Database',
    short_description: 'Engine: 1 soru → 5 farklı analoji.',
    kind: 'engine_behavior',
  },
  {
    code: 'C6-T05',
    module_code: 'C6',
    name: 'Soru Tohumlama',
    name_en: 'Question Seeding',
    short_description: 'Engine: dersin başında merak uyandıran soru.',
    kind: 'engine_behavior',
  },
]
const C7: TechniqueSeed[] = [
  {
    code: 'C7-T01',
    module_code: 'C7',
    name: 'Gecikmeli Geri Bildirim',
    name_en: 'Delayed Feedback',
    short_description: "Engine: cevap yarın sabah 9'da hatırlatılır.",
    kind: 'engine_behavior',
  },
  {
    code: 'C7-T02',
    module_code: 'C7',
    name: 'Hata Portföyü',
    name_en: 'Error Portfolio',
    short_description: 'Engine: tüm yanlışlar "en değerli hatalarım" klasöründe.',
    kind: 'engine_behavior',
  },
  {
    code: 'C7-T03',
    module_code: 'C7',
    name: 'Rubrik Şeffaflığı',
    name_en: 'Rubric Transparency',
    short_description: 'Engine: "neden 6 puan aldı?" detay açıklama.',
    kind: 'engine_behavior',
  },
  {
    code: 'C7-T04',
    module_code: 'C7',
    name: 'Metaforik Düzeltme',
    name_en: 'Metaphorical Correction',
    short_description: 'Engine: "Köprü çöker, doğrusu sağlam durur" tipi düzeltme.',
    kind: 'engine_behavior',
  },
  {
    code: 'C7-T05',
    module_code: 'C7',
    name: '5 Neden',
    name_en: '5 Whys',
    short_description: 'Engine: yanlışın kök nedenini 5 "neden" ile bulma.',
    kind: 'engine_behavior',
  },
]
const C8: TechniqueSeed[] = [
  {
    code: 'C8-T01',
    module_code: 'C8',
    name: '1 Sayfa Kuralı',
    name_en: '1-Page Rule',
    short_description: 'Engine: her konunun 1 sayfa brief özetini zorunlu kılma.',
    kind: 'engine_behavior',
  },
  {
    code: 'C8-T02',
    module_code: 'C8',
    name: 'Sahte Kitle',
    name_en: 'Imaginary Audience',
    short_description: 'Engine: "Patronuna sunacakmış gibi hazırla" kalite kaldıracı.',
    kind: 'engine_behavior',
  },
  {
    code: 'C8-T03',
    module_code: 'C8',
    name: 'Günlük Keşif',
    name_en: 'Daily Discovery',
    short_description: 'Engine: her gün 1 acayip bilgi push bildirimi.',
    kind: 'engine_behavior',
  },
  {
    code: 'C8-T04',
    module_code: 'C8',
    name: 'Reconstruction',
    name_en: 'Reconstruction',
    short_description: 'Engine: öğrenileni kapatıp sıfırdan ezberden çizme.',
    kind: 'engine_behavior',
  },
  {
    code: 'C8-T05',
    module_code: 'C8',
    name: 'Zincirleme Açıklama',
    name_en: 'Chain Explanation',
    short_description: 'Engine: her cümle öncekinin doğrudan sonucu olmalı.',
    kind: 'engine_behavior',
  },
]
const C9: TechniqueSeed[] = [
  {
    code: 'C9-T01',
    module_code: 'C9',
    name: 'Rastgele Girdi',
    name_en: 'Random Input',
    short_description: 'Engine: tıkanıklıkta rastgele kelimeyle konuyu ilişkilendirme.',
    kind: 'engine_behavior',
  },
  {
    code: 'C9-T02',
    module_code: 'C9',
    name: 'Disney Stratejisi',
    name_en: 'Disney Creativity',
    short_description: 'Engine: Hayalperest → Gerçekçi → Eleştirmen 3 fazı.',
    kind: 'engine_behavior',
  },
  {
    code: 'C9-T03',
    module_code: 'C9',
    name: 'PMI Tekniği',
    name_en: 'PMI (Plus/Minus/Interesting)',
    short_description: 'Engine: fikrin artı, eksi ve ilginç yönlerini ayırma.',
    kind: 'engine_behavior',
  },
  {
    code: 'C9-T04',
    module_code: 'C9',
    name: 'Morfolojik Sentez',
    name_en: 'Morphological Synthesis',
    short_description: 'Engine: problem parametrelerinin kombinasyonlarını tablolama.',
    kind: 'engine_behavior',
  },
  {
    code: 'C9-T05',
    module_code: 'C9',
    name: 'Yabancılaştırma',
    name_en: 'Defamiliarization',
    short_description: 'Engine: "Zürafa = bulutları yiyen kule" tipi betimleme.',
    kind: 'engine_behavior',
  },
]
const C10: TechniqueSeed[] = [
  {
    code: 'C10-T01',
    module_code: 'C10',
    name: 'Ön Test Etkisi',
    name_en: 'Pre-testing Effect',
    short_description: 'Engine: konu anlatılmadan soru sor; yanlış cevap öğrenmeyi %20 artırır.',
    kind: 'engine_behavior',
    ui_component: 'quiz',
  },
  {
    code: 'C10-T02',
    module_code: 'C10',
    name: 'Seçenek Madenciliği',
    name_en: 'Option Mining',
    short_description: 'Engine: yanlış şıkların neden yanlış olduğunu açıklatma.',
    kind: 'engine_behavior',
  },
  {
    code: 'C10-T03',
    module_code: 'C10',
    name: 'Beyaz Sayfa Provası',
    name_en: 'Brain Dump',
    short_description: 'Engine: sınav öncesi 10 dk boş kağıda her şeyi dökme.',
    kind: 'engine_behavior',
  },
  {
    code: 'C10-T04',
    module_code: 'C10',
    name: 'Zihinsel Kontrast (WOOP)',
    name_en: 'Mental Contrasting',
    short_description: 'Engine: başarıyı + yoldaki engelleri detaylıca hayal etme.',
    kind: 'engine_behavior',
  },
  {
    code: 'C10-T05',
    module_code: 'C10',
    name: 'Sınav Sonrası Otopsi',
    name_en: 'Post-exam Autopsy',
    short_description: 'Engine: "Nerede zaman kaybettin?" detaylı analiz.',
    kind: 'engine_behavior',
  },
]

export const ALL_TECHNIQUES: TechniqueSeed[] = [
  ...M1,
  ...M2,
  ...M3,
  ...M4,
  ...M5,
  ...M6,
  ...M7,
  ...C1,
  ...C2,
  ...C3,
  ...C4,
  ...C5,
  ...C6,
  ...C7,
  ...C8,
  ...C9,
  ...C10,
]

// Assert toplam 150
if (ALL_TECHNIQUES.length !== 150) {
  console.warn(`⚠️ Teknik sayısı ${ALL_TECHNIQUES.length}, 150 bekleniyordu`)
}
